In [1]:
list1 = [ 1, 2, 3, 4 ]
print(list1)
print(list1[0])

# Lists can have multiple data types
list2 = ["John Elder", 1, list1, True]
print(list2)

[1, 2, 3, 4]
1
['John Elder', 1, [1, 2, 3, 4], True]


In [2]:
# Harder to deal with lists with normal python operations if the lists are large
# Use numpy array instead
# numpy = Numeric Python

import numpy as np

# ndarray = n dimensional array
np1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# np.shape: provides shape of array
print("np1.shape =", np1.shape)

# np.arange: used to create a numpy array
np2 = np.arange(10)
print("np.arange(10) =", np2) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# np.arange(begin, end, step)
np3 = np.arange(0, 10, 2)
print("np.arange(0, 10, 2) =", np3) # [0, 2, 4, 6, 8]

# np.zeros: create array of zeroes
np4 = np.zeros(10)
print("np.zeros(10) =", np4)

# np.zeros((dimension, 10))
np5 = np.zeros((2, 10))
print("np.zeros(2,10) =", np5) # [[0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0]]

# np.full((dimensions, # items), value): Populate an array with n number of items with the value specified
np6 = np.full((2, 5), 7)
print("np.full((2, 5), 7) =", np6)  # [[7, 7, 7, 7, 7], [7, 7, 7, 7, 7]]

# Convert python list to np
list2 = [1, 2, 3, 4, 5]
np7 = np.array(list2)
print("np.array([1, 2, 3, 4, 5]) =", np7) # [1, 2, 3, 4, 5]

# indexing np array
print("np7[2] =", np7[2]) # 3

np1.shape = (10,)
np.arange(10) = [0 1 2 3 4 5 6 7 8 9]
np.arange(0, 10, 2) = [0 2 4 6 8]
np.zeros(10) = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
np.zeros(2,10) = [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
np.full((2, 5), 7) = [[7 7 7 7 7]
 [7 7 7 7 7]]
np.array([1, 2, 3, 4, 5]) = [1 2 3 4 5]
np7[2] = 3


In [4]:
# Slicing Numpy Arrays: Does not modify original array
np1 = np.arange(1, 10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("np1 =", np1)

# Slice and return 2, 3, 4, 5
print("np1[1:5] =", np1[1:5])

# Return from n till end of array
print("np1[3:] =", np1[3:])

# Negative slices
print("np1[-3: -1] =", np1[-3: -1])  # [7, 8]

# Slices with steps 
print("np1[1:5:2] =", np1[1:5:2]) # [2, 4]

# Steps on entire array
print("np1[::2] =", np1[::2]) # [1, 3, 5, 7, 9]

# Slice 2-d array
np2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("\nnp2 =", np2)

# Access in 2d array
print("np2[1, 2] =", np2[1, 2])   # 8

# Slice 2d array
print("np2[0:1, 1:3] =", np2[0:1, 1:3]) # [[2, 3]]
print("np2[:, 1:3] =", np2[:, 1:3])   # [[2, 3], [7, 8]]

np1 = [1 2 3 4 5 6 7 8 9]
np1[1:5] = [2 3 4 5]
np1[3:] = [4 5 6 7 8 9]
np1[-3: -1] = [7 8]
np1[1:5:2] = [2 4]
np1[::2] = [1 3 5 7 9]

np2 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
np2[1, 2] = 8
np2[0:1, 1:3] = [[2 3]]
np2[:, 1:3] = [[2 3]
 [7 8]]


In [5]:
# Universal Functions
np1 = np.arange(10)
print("np1 =", np1)

# np.sqrt(<nd-arr>): Find square root of every element
print("\nnp.sqrt(np1)) =", np.sqrt(np1))

# np.absolute(<nd-arr>): Absolute value
print("\nnp.absolute(np1) =", np.absolute(np1))

# np.exp(<nd-arr>: Exponent
print("\nnp.exp(np1) =", np.exp(np1))

# Min/Max
print("\nnp.max(np1) =", np.max(np1))
print("np.min(np1) =", np.min(np1))

# Sign: Positive or negative
print("\nnp.sign(np1) =", np.sign(np1))

# Trig: sin, cos, log
print("\nnp.sin(np1) =", np.sin(np1))

np1 = [0 1 2 3 4 5 6 7 8 9]

np.sqrt(np1)) = [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

np.absolute(np1) = [0 1 2 3 4 5 6 7 8 9]

np.exp(np1) = [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]

np.max(np1) = 9
np.min(np1) = 0

np.sign(np1) = [0 1 1 1 1 1 1 1 1 1]

np.sin(np1) = [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [6]:
''' 
Copy vs View for NumPy
 Copy is a copy of an array (deep copy)
 View is a copy of an array, connected to the original array (pointer to original array)
'''
np1 = np.arange(6)
print("np1 =", np1)

# Create view 
np2 = np1.view()
print(f'Original np1 {np1}')
print(f'Original np2 = np1.view() = {np2}')

np2[0] = 41
print("\nModify np1[0] = 41")
print(f'Changed np1 {np1}')
print(f'Original np2 {np2}')

# Create a copy
np3 = np.arange(6)
np4 = np3.copy()

print(f'\nOriginal np3 {np3}')
print(f'Original np4 = np3.copy() = {np4}')

np4[0]=41
print('\nnp3[0] = 41')
print(f'Changed np3 {np3}')
print(f'Original np4 = np3.copy() = {np4}')

np1 = [0 1 2 3 4 5]
Original np1 [0 1 2 3 4 5]
Original np2 = np1.view() = [0 1 2 3 4 5]

Modify np1[0] = 41
Changed np1 [41  1  2  3  4  5]
Original np2 [41  1  2  3  4  5]

Original np3 [0 1 2 3 4 5]
Original np4 = np3.copy() = [0 1 2 3 4 5]

np3[0] = 41
Changed np3 [0 1 2 3 4 5]
Original np4 = np3.copy() = [41  1  2  3  4  5]


In [7]:
# Shape and Reshape Numpy Arrays

# Create 1-D numpy array and get shape
np1 = np.arange(1, 13)
print(f'np1 = {np1}')
print(f'np1.shape = {np1.shape}')

# Create 2-D numpy array and get shape (rows/columns)
np2 = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(f'\nnp2 = {np2}')
print(f'np2.shape = {np2.shape}')

# Reshape 2-D
np3 = np1.reshape(3, 4) # 3 rows, with 4 items in each
print(f'\nnp1.reshape(3, 4) = {np3}')
print(f'np3.shape = {np3.shape}')

# Reshape 3-D
np4 = np1.reshape(2, 3, 2) # 3-D, with 3 rows or 2
print(f'\nnp4.reshape(2, 3, 2) = {np4}')
print(f'np4.shape = {np4.shape}')

# Flatten to 1-D
np5 = np4.reshape(-1)
print(f'\nnp4.reshape(-1) = {np5}')
print(f'np5.shape = {np5.shape}')

np1 = [ 1  2  3  4  5  6  7  8  9 10 11 12]
np1.shape = (12,)

np2 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
np2.shape = (2, 6)

np1.reshape(3, 4) = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
np3.shape = (3, 4)

np4.reshape(2, 3, 2) = [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
np4.shape = (2, 3, 2)

np4.reshape(-1) = [ 1  2  3  4  5  6  7  8  9 10 11 12]
np5.shape = (12,)


In [8]:
# Iterate through numpy arrays

# 1D loop
np1 = np.arange(1, 11)
print('\nLooping 1D Array')
for x in np1:
    print(x, end=' ')
print()

# 2D Loop
np2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('\nLooping 2D Array')
for x in np2:
    print(x)
    for y in x:
        print(y, end=" ")
    print()

# 3D Array
print('\nLooping 3D Arr')
np3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
for x in np3:
    # print(x)
    for y in x:
        # print(y)
        for z in y:
            print(z, end=" ")

print('\n\n using np.nditer(<nd-arr>)')
# Use np.nditer()
for x in np.nditer(np3):
    print(x, end=" ")


Looping 1D Array
1 2 3 4 5 6 7 8 9 10 

Looping 2D Array
[1 2 3 4 5]
1 2 3 4 5 
[ 6  7  8  9 10]
6 7 8 9 10 

Looping 3D Arr
1 2 3 4 5 6 7 8 9 10 11 12 

 using np.nditer(<nd-arr>)
1 2 3 4 5 6 7 8 9 10 11 12 

In [9]:
# Sorting Numpy Arrays

# np.sort(<nd-arr>): Does not modify the original array
np1 = np.array([6, 7, 4, 9, 0, 2, 1])
print(f'np1 = {np1}')
print(f'np.sort(np1) = {np.sort(np1)}')

# Alphabetical Sorting (lexicographic)
np2 = np.array(["John", "Tina", "Aaron", "Zed"])
print(f'\nnp2 = {np2}')
print(f'np.sort(np2) = {np.sort(np2)}')

# Booleans T/F
np3 = np.array([True, False, False, True])
print(f'\nnp3 = {np3}')
print(f'np.sort(np3) = {np.sort(np3)}')

# 2-D
np4 = np.array([[6, 7, 1, 9], [8, 3, 5, 0]])
print(f'\nnp4 = {np4}')
print(f'np.sort(np4) = {np.sort(np4)}')

np1 = [6 7 4 9 0 2 1]
np.sort(np1) = [0 1 2 4 6 7 9]

np2 = ['John' 'Tina' 'Aaron' 'Zed']
np.sort(np2) = ['Aaron' 'John' 'Tina' 'Zed']

np3 = [ True False False  True]
np.sort(np3) = [False False  True  True]

np4 = [[6 7 1 9]
 [8 3 5 0]]
np.sort(np4) = [[1 6 7 9]
 [0 3 5 8]]


In [10]:
# Searching Numpy Arrays

np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3])
print(f'np1 = {np1}')

x = np.where(np1 == 3) # Returns index numbers where value is 3
print(f'\nnp.where(np1 == 3) = {x[0]}')

# Return index of even items 
y = np.where(np1 % 2 == 0) 
print(f'\nnp.where(np1 % 2 == 3) = {y[0]}')

np1 = [ 1  2  3  4  5  6  7  8  9 10  3]

np.where(np1 == 3) = [ 2 10]

np.where(np1 % 2 == 3) = [1 3 5 7 9]


In [11]:
# Filtering numpy arrays with boolean index lists

np1 = np.arange(1, 11)
print(f'np1 = {np1}')

x = [True, True, False, False, False, False, False, False, False, False]
print(np1[x]) # Filters all false values

print()
filtered = []
for thing in np1:
    if thing % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)
print(f'filtered = {filtered}')
print(f'np1[filtered] = {np1[filtered]}')

# Built-in shortcut
print()
filtered = np1 % 2 == 0
print(f'filtered = {filtered}')
print(f'np1[filtered] = {np1[filtered]}')

np1 = [ 1  2  3  4  5  6  7  8  9 10]
[1 2]

filtered = [False, True, False, True, False, True, False, True, False, True]
np1[filtered] = [ 2  4  6  8 10]

filtered = [False  True False  True False  True False  True False  True]
np1[filtered] = [ 2  4  6  8 10]
